name: NuGet Build & Publish

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
          
      - name: Build solution and generate NuGet package
        run: |  
          cd src
          dotnet build -c Release
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./Win32Utils/out/*.nupkg --skip-duplicate --no-symbols true -k ${{ secrets.NUGET_KEYS }} -s https://api.nuget.org/v3/index.json
