name: NuGet Build & Publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1

      - name: Build
        run: |
          cd src
          dotnet build -c Release
          dotnet pack -c Release -o out

      - name: Push
        run: |
         cd src/out
         dotnet nuget push *.nupkg --skip-duplicate --no-symbols -k ${{ secrets.NUGET_KEYS }} -s https://api.nuget.org/v3/index.json
